# Generated by Django 5.0.4 on 2025-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='テーブル名')),
                ('status', models.CharField(choices=[('vacant', '空席'), ('occupied', '使用中'), ('cleaning', '清掃中')], default='vacant', max_length=20, verbose_name='ステータス')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
