# Generated by Django 5.0.4 on 2025-01-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0002_tablerow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeManagementTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('col1', models.CharField(blank=True, max_length=255, null=True)),
                ('col2', models.CharField(blank=True, max_length=255, null=True)),
                ('col3', models.CharField(blank=True, max_length=255, null=True)),
                ('col4', models.CharField(blank=True, max_length=255, null=True)),
                ('col5', models.CharField(blank=True, max_length=255, null=True)),
                ('col6', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TableRow',
        ),
    ]
