# Generated by Django 5.0.4 on 2025-01-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0003_timemanagementtable_delete_tablerow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timemanagementtable',
            name='col6',
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col2',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col3',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col4',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col5',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
