# Generated by Django 5.0.4 on 2025-01-28 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0004_remove_timemanagementtable_col6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プラン名'),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='テーブル番号'),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col3',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='名数'),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col4',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2359)], verbose_name='開始時間(24時間表記)'),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col5',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2359)], verbose_name='終了時間(24時間表記)'),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='row_id',
            field=models.IntegerField(verbose_name='行番号'),
        ),
    ]
