# Generated by Django 5.0.4 on 2025-02-05 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0005_alter_timemanagementtable_col1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timemanagementtable',
            name='col2',
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col1',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='テーブル番号'),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col4',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2359)], verbose_name='開始時間(整数4桁)'),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col5',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2359)], verbose_name='終了時間(整数4桁)'),
        ),
    ]
