# Generated by Django 5.0.4 on 2025-02-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0007_seatingstatus_delete_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemanagementtable',
            name='col2',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='テーブル番号'),
        ),
        migrations.AlterField(
            model_name='timemanagementtable',
            name='col1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プラン名'),
        ),
    ]
