# Generated by Django 5.0.4 on 2025-02-24 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0009_timemanagementtable_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeManagementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('row_number', models.IntegerField()),
                ('plan_name', models.CharField(blank=True, max_length=100)),
                ('table_number', models.CharField(blank=True, max_length=50)),
                ('people_count', models.IntegerField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=5)),
                ('end_time', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='SeatingStatus',
        ),
        migrations.DeleteModel(
            name='TimeManagementTable',
        ),
    ]
