# Generated by Django 5.0.4 on 2025-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0010_timemanagementrecord_delete_seatingstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemanagementrecord',
            name='col11',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timemanagementrecord',
            name='col12',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timemanagementrecord',
            name='extensions',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timemanagementrecord',
            name='invoiceChecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timemanagementrecord',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timemanagementrecord',
            name='out_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timemanagementrecord',
            name='paymentChecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timemanagementrecord',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timemanagementrecord',
            name='stay',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timemanagementrecord',
            name='water_counts',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timemanagementrecord',
            name='water_time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
