# Generated by Django 5.0.4 on 2025-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0011_timemanagementrecord_col11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemanagementrecord',
            name='water_override',
            field=models.IntegerField(default=0),
        ),
    ]
