# Generated by Django 5.0.4 on 2025-03-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0012_timemanagementrecord_water_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemanagementrecord',
            name='col11',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timemanagementrecord',
            name='col12',
            field=models.CharField(max_length=20),
        ),
    ]
