# Generated by Django 4.2.20 on 2025-04-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EatryHub', '0004_store'),
        ('TimeManagement', '0013_alter_timemanagementrecord_col11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemanagementrecord',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EatryHub.store'),
            preserve_default=False,
        ),
    ]
