# Generated by Django 4.2.20 on 2025-03-26 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatryHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'このユーザー名は既に存在します。'}, help_text='日本語・英数字・記号を使用できます', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='ユーザー名には日本語（漢字・ひらがな・カタカナ）、英数字、@/./+/-/_ のみ使用可能です', regex='^[\\u4E00-\\u9FFF\\u3040-\\u309F\\u30A0-\\u30FF\\w.@+-]+$')], verbose_name='ユーザー名'),
        ),
    ]
