# Generated by Django 4.2.20 on 2025-03-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatryHub', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('progress', models.FloatField(default=0.0)),
            ],
        ),
    ]
