# Generated by Django 4.2.20 on 2025-04-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EatryHub', '0005_customuser_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('capacity', models.IntegerField(default=4)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EatryHub.store')),
            ],
            options={
                'unique_together': {('store', 'table_number')},
            },
        ),
    ]
